---
  CinderVolumes.create_volume:
    -
      args:
        size: 1
      runner:
        type: "constant"
        times: 30
        concurrency: 5
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        quotas:
            cinder:
                volumes: -1
